# Generated by Django 4.2.7 on 2023-12-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input1', models.CharField(max_length=100)),
                ('text_input2', models.CharField(max_length=100)),
                ('dropdown_value1', models.CharField(max_length=50)),
                ('dropdown_value2', models.CharField(max_length=50)),
            ],
        ),
    ]
